dataset:
  train:
    dataroot_gt: /home/yuxin/StableVSR/Datasets/REDS/train/train_blur/ # path to GT (e.g., 000, 001, 002 ... )
    dataroot_lq: /home/yuxin/StableVSR/Datasets/REDS/train/train_blur_bicubic/X4/ # path to bicubic (e.g., 000, 001, 002 ... )
    meta_info_file: /home/yuxin/StableVSR/dataset/REDS_train_metadata.txt
    dataroot_flow:
    io_backend:
      type: disk
    num_frame: 3
    val_partition: 'REDS4'
    test_mode: False
    interval_list: [1]
    random_reverse: False
    gt_size: 256
    use_hflip: True
    use_rot: False
    scale: 4
    remove_partition: True
  test:
    dataroot_gt: /home/yuxin/StableVSR/Datasets/REDS/test/test_blur/
    dataroot_lq: /home/yuxin/StableVSR/Datasets/REDS/test/test_blur_bicubic/X4/
    meta_info_file: /home/yuxin/StableVSR/dataset/REDS_test_metadata.txt
    io_backend:
      type: disk
    num_frame: 3
    val_partition: 'REDS4'
    test_mode: True
    interval_list: [1]
    random_reverse: False
    gt_size: 256
    use_hflip: False
    use_rot: False
    scale: 4